### ISSUE TITLE
Maven artefacts not synced to maven central?

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/action-publish-mvn#1]
I had expected to find something at https://search.maven.org/search?q=io.cucumber.test-release-automation after the test workflow passed, but there is nothing there.

Check back to see if it appears later (in case the nexus->central sync needs several hours).

**Comment by mpkorstanje** [comment]
The search index and the repository are also updated by separate processes. 

If you browse the repository the artifacts there quite quickly:

https://repo1.maven.org/maven2/io/cucumber/test-release-automation/

**Comment by mpkorstanje** [comment]
Usually though, if the release process succeeds the artifacts are released.

I guess you could double check against:

https://oss.sonatype.org/service/local/repositories/releases/content/io/cucumber/

**Comment by aslakhellesoy** [comment]
Ah. It's there now in the search index too - https://search.maven.org/search?q=a:test-release-automation. Closing this.
