### ISSUE TITLE
Verify that a release is published

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/action-publish-mvn#2]
See https://github.com/cucumber/action-publish-mvn/issues/1#issuecomment-926444454

We should verify that the release has uploaded something, similar to how npm is tested: https://github.com/cucumber/action-publish-npm/blob/2ddb9c9797cfe9622abff0421745b9b8efb0fa6f/.github/workflows/test.yaml#L32

**Comment by mattwynne** [comment]
Looks like we should be able to check for a URL like this one: https://oss.sonatype.org/service/local/repositories/releases/content/io/cucumber/cucumber-parent/2.3.2/cucumber-parent-2.3.2.pom
